---
- name: Ansible check directory.
  stat:
    path: /tmp/docker_image_build
  register: my_folder

- name: "Ansible Create directory if not exists"
  file:
    path: /tmp/docker_image_build
    state: directory
  when: my_folder.stat.exists == false

- name: copy files [local -> remote]
  copy:
    src: ./roles/docker_image_build/templates/docker_dir
    dest: /tmp/docker_image_build

- name: Build Docker image from Dockerfile ( name will be -> "web_image" )
  docker_image:
    name: web_image
    path: /tmp/docker_image_build/docker_dir
    state: build
