version: '3'

services:
  docker-registry:
    image: registry:2
    container_name: docker-registry
    ports:
      - {{ x_port }}:{{ x_port }}
    restart: always
    volumes:
      - ./volume:/var/lib/registry
  docker-registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: docker-registry-ui
    ports:
      - {{ ui_port }}:{{ ui_port_2 }}
    environment:
      ENV_DOCKER_REGISTRY_HOST: docker-registry
      ENV_DOCKER_REGISTRY_PORT: {{ x_port }}
